import { VerbFlashcards } from ".";

export const presentParticiple: VerbFlashcards = {
  run: 'running',
  eat: 'eating',
  drink: 'drinking',
  jump: 'jumping',
  sleep: 'sleeping',
  play: 'playing',
  sing: 'singing',
  dance: 'dancing',
  laugh: 'laughing',
  cry: 'crying',
  brush: 'brushing',
  wash: 'washing',
  study: 'studying',
  read: 'reading',
  write: 'writing',
  draw: 'drawing',
  cook: 'cooking',
  clean: 'cleaning',
  watch: 'watching',
  listen: 'listening',
  swim: 'swimming',
  make: 'making',
  bake: 'baking',
  take: 'taking',
  sit: 'sitting',
  get: 'getting',
  put: 'putting',
  cut: 'cutting',
  tie: 'tying',
  hug: 'hugging'
};