import { VerbFlashcards } from "..";

export const simplePast: VerbFlashcards = {
  run: 'ran',
  eat: 'ate',
  drink: 'drank',
  jump: 'jumped',
  sleep: 'slept',
  play: 'played',
  sing: 'sang',
  dance: 'danced',
  laugh: 'laughed',
  cry: 'cried',
  brush: 'brushed',
  wash: 'washed',
  study: 'studied',
  read: 'read',
  write: 'wrote',
  draw: 'drew',
  cook: 'cooked',
  clean: 'cleaned',
  watch: 'watched',
  listen: 'listened',
  swim: 'swam',
  make: 'made',
  bake: 'baked',
  take: 'took',
  sit: 'sat',
  get: 'got',
  put: 'put',
  cut: 'cut',
  tie: 'tied',
  hug: 'hugged'
}