const whatList = [
  'Dancing',
  'Skydiving',
  'Juggling',
  'Playing hopscotch',
  'Eating spaghetti',
  'Riding a unicycle',
  'Painting a masterpiece',
  'Breakdancing',
  'Singing in the rain',
  'Bungee jumping',
  'Yoga on a mountaintop',
  'Knitting a scarf',
  'Cooking pancakes',
  'Surfing a tsunami',
  'Karate chopping bricks',
  'Balancing on a tightrope',
  'Playing the accordion',
  'Building a sandcastle',
  'Sumo wrestling',
  'Hula hooping',
  'Riding a skateboard',
  'Doing a magic trick',
  'Running a marathon',
  'Playing the guitar',
  'Ice skating',
  'Juggling fire',
  'Karaoke singing',
  'Performing stand-up comedy',
  'Playing the piano',
  'Acting in a Shakespeare play',
  'Rock climbing',
  'DJing',
  'Gardening',
  'Pogo stick jumping',
  'Making a sandwich',
  'Riding a hot air balloon',
  'Ice fishing',
  'Doing cartwheels',
  'Playing frisbee',
  'Racing a snail',
  'Water skiing with dolphins',
  'Playing hide and seek',
  'Building a robot',
  'Playing chess',
  'Doing a somersault',
  'Jumping on a trampoline',
  'Flying a kite',
  'Designing a fashion show',
  'Baking a giant cake',
  'Surfing on a rainbow',
  'Playing soccer',
  'Singing with a choir of cats',
  'Juggling watermelons',
  'Yoga with dinosaurs',
  'Cooking with a flamethrower',
  'Painting a mural',
  'Snorkeling in a coral reef',
  'Hiking through a jungle',
  'Skiing down a mountain',
  'Fencing',
  'Zip-lining',
  'Whale watching from a boat',
  'Archery with rubber chickens',
  'Horseback riding on a rainbow',
  'Tap dancing',
  'Synchronized swimming',
  'Mountain biking',
  'Doing parkour',
  'Trick-or-treating',
  'Ballet dancing',
  'Rollerblading',
  'Playing ping pong',
  'Fishing',
  'Hitchhiking',
];
