const whoList = [
  'Albert Einstein',
  'Wonder Woman',
  'Elvis Presley',
  'Yoda',
  'Sherlock Holmes',
  'Beyoncé',
  'Captain Jack Sparrow',
  'Darth Vader',
  'Harry Potter',
  'Marilyn Monroe',
  'Spider-Man',
  'Cleopatra',
  'Batman',
  'Charlie Chaplin',
  'Pikachu',
  'James Bond',
  'Elsa (from Frozen)',
  'The Hulk',
  'Cleopatra',
  'Mickey Mouse',
  'Superman',
  'Gandalf',
  'Captain America',
  'Princess Leia',
  'Dracula',
  'The Joker',
  'Frida Kahlo',
  'Black Widow',
  'Hermione Granger',
  'Iron Man',
  'Thor',
  'Vincent van Gogh',
  'Mother Teresa',
  'Michael Jackson',
  'Walt Disney',
  'Pablo Picasso',
  'Neil deGrasse Tyson',
  'A Firefighter',
  'An Astronaut',
  'A Teacher',
  'A Doctor',
  'A Chef',
  'A Police Officer',
  'An Artist',
  'A Pilot',
  'An Engineer',
  'An Athlete',
  'A Scientist',
  'A Musician',
  'A Writer',
  'A Dancer',
  'An Actor',
  'A Photographer',
  'A Journalist',
  'An Explorer',
  'An Architect',
  'An Inventor',
  'A Soldier',
  'A Singer',
  'A Fashion Designer',
  'A Philosopher',
  'A Magician',
  'A Zookeeper',
  'A Biologist',
  'An Astronomer',
  'A Surgeon',
  'A Psychologist',
  'A Botanist',
  'A Veterinarian',
  'A Paleontologist',
  'An Athlete',
  'An Archaeologist',
  'A Marine Biologist',
  'A Chef',
  'A Farmer',
  'A Librarian',
  'A Pilot',
  'A Police Officer',
  'A News Anchor',
  'An Explorer',
  'A Bus Driver',
  'A Construction Worker',
  'A Nurse',
  'A Detective',
  'A Pirate',
  'A Cowboy',
  'A Superhero',
  'A Vampire',
  'A Wizard',
  'A Princess',
  'A Pirate',
  'A Mad Scientist',
  'A Spy',
  'A Robot',
  'A Witch',
  'A Fairy',
  'A Mermaid',
  'A Dragon',
  'A Unicorn',
  'A Lion',
  'An Elephant',
  'A Dolphin',
  'A Tiger',
  'A Penguin',
  'A Giraffe',
  'A Kangaroo',
  'A Butterfly',
  'A Panda',
  'A Zebra',
  'A Koala',
  'An Owl',
  'A Penguin',
  'A Seal',
  'A Sloth',
  'A Cheetah',
  'A Gorilla',
  'A Polar Bear',
  'A Kangaroo',
  'An Elephant',
  'A Dolphin',
  'A Tiger',
  'A Penguin',
  'A Giraffe',
  'A Kangaroo',
  'A Butterfly',
  'A Panda',
  'A Zebra',
  'A Koala',
  'An Owl',
  'A Penguin',
  'A Seal',
  'A Sloth',
  'A Cheetah',
  'A Gorilla',
  'A Polar Bear',
];
