import { VerbFlashcards } from '.';

export const pastParticiple: VerbFlashcards = {
  run: 'run',
  eat: 'eaten',
  drink: 'drunk',
  jump: 'jumped',
  sleep: 'slept',
  play: 'played',
  sing: 'sung',
  dance: 'danced',
  laugh: 'laughed',
  cry: 'cried',
  brush: 'brushed',
  wash: 'washed',
  study: 'studied',
  read: 'read',
  write: 'written',
  draw: 'drawn',
  cook: 'cooked',
  clean: 'cleaned',
  watch: 'watched',
  listen: 'listened',
  swim: 'swum',
  make: 'made',
  bake: 'baked',
  take: 'taken',
  sit: 'sat',
  get: 'gotten',
  put: 'put',
  cut: 'cut',
  tie: 'tied',
  hug: 'hugged',
};
