const whereList = [
  'Underwater city',
  'In an ancient pyramid',
  'In Candyland',
  'In outer space',
  'In a secret garden',
  'At a time-traveling circus',
  'In a haunted mansion',
  'In the Mushroom kingdom',
  'On a volcanic island',
  'In a robot factory',
  'On a moon base',
  'In a fairy tale castle',
  'In a Wild West saloon',
  'In an ice cream factory',
  'On a pirate ship',
  'In the Amazon rainforest',
  'In a disco nightclub',
  'On a Mars colony',
  'In an art museum',
  "In a wizard's tower",
  'At a rollercoaster park',
  'On an alien spaceship',
  'In a sunflower field',
  'In a chocolate factory',
  'In a Jurassic jungle',
  'In an Arabian desert',
  'In a cyberpunk city',
  'In the Mushroom kingdom',
  'In a candy cane forest',
  'Under the rainbow',
  'On a steampunk train',
  'At a secret agent headquarters',
  'At a tropical paradise',
  'At an amusement park',
  'On a space station',
  'During a robot apocalypse',
  'On a moonlit beach',
  'In a parallel universe',
  'In a jungle treehouse',
  'On a frozen tundra',
  'In Atlantis',
  'In a pixelated video game world',
  'In a haunted graveyard',
  'In a floating city in the clouds',
  'In a candy spaceship',
  'At the lost city of gold',
  'In an enchanted forest',
  'On a mountain summit',
  'In a secret laboratory',
  'At the center of the Earth',
];
