const whoList = [
  'Albert Einstein',
  'Wonder Woman',
  'Elvis Presley',
  'Yoda',
  'Sherlock Holmes',
  'Beyoncé',
  'Captain Jack Sparrow',
  'Darth Vader',
  'Oprah Winfrey',
  'Harry Potter',
  'Marilyn Monroe',
  'Spider-Man',
  'Cleopatra',
  'Batman',
  'Charlie Chaplin',
  'Pikachu',
  'James Bond',
  'Elsa (from Frozen)',
  'The Hulk',
  'Cleopatra',
  'Mickey Mouse',
  'Sherlock Holmes',
  'Superman',
  'Gandalf',
  'Captain America',
  'Princess Leia',
  'Dracula',
  'Princess Peach',
  'The Joker',
  'Frida Kahlo',
  'Black Widow',
  'The Mad Hatter',
  'Hermione Granger',
  'Iron Man',
  'The Queen of Hearts',
  'Thor',
  'Leonardo da Vinci',
  'Amelia Earhart',
  'Nelson Mandela',
  'Marie Curie',
  'Neil Armstrong',
  'Malala Yousafzai',
  'Charlie Brown',
  'Coco Chanel',
  'Vincent van Gogh',
  'Mother Teresa',
  'Stephen Hawking',
  'Audrey Hepburn',
  'Martin Luther King Jr.',
  'Queen Elizabeth II',
  'Michael Jackson',
  'Walt Disney',
  'Jane Goodall',
  'Pablo Picasso',
  'Neil deGrasse Tyson',
  'Beethoven',
  'Jane Austen',
  'Ellen DeGeneres',
  'Alberto Santos-Dumont',
  'Ada Lovelace',
  'Firefighter',
  'Astronaut',
  'Teacher',
  'Doctor',
  'Chef',
  'Police Officer',
  'Artist',
  'Pilot',
  'Engineer',
  'Athlete',
  'Scientist',
  'Musician',
  'Writer',
  'Dancer',
  'Actor',
  'Photographer',
  'Journalist',
  'Explorer',
  'Architect',
  'Inventor',
  'Soldier',
  'Singer',
  'Fashion Designer',
  'Philosopher',
  'Magician',
  'Zookeeper',
  'Biologist',
  'Astronomer',
  'Surgeon',
  'Psychologist',
  'Botanist',
  'Veterinarian',
  'Paleontologist',
  'Athlete',
  'Archaeologist',
  'Marine Biologist',
  'Chef',
  'Farmer',
  'Librarian',
  'Pilot',
  'Police Officer',
  'News Anchor',
  'Explorer',
  'Bus Driver',
  'Construction Worker',
  'Nurse',
  'Detective',
  'Pirate',
  'Cowboy',
  'Superhero',
  'Vampire',
  'Wizard',
  'Princess',
  'Pirate',
  'Mad Scientist',
  'Spy',
  'Robot',
  'Witch',
  'Space Explorer',
  'Time Traveler',
  'Fairy',
  'Mermaid',
  'Dragon',
  'Unicorn',
  'Lion',
  'Elephant',
  'Dolphin',
  'Tiger',
  'Penguin',
  'Giraffe',
  'Kangaroo',
  'Butterfly',
  'Panda',
  'Zebra',
  'Koala',
  'Owl',
  'Penguin',
  'Seal',
  'Sloth',
  'Cheetah',
  'Gorilla',
  'Polar Bear',
  'Kangaroo',
  'Elephant',
  'Dolphin',
  'Tiger',
  'Penguin',
  'Giraffe',
  'Kangaroo',
  'Butterfly',
  'Panda',
  'Zebra',
  'Koala',
  'Owl',
  'Penguin',
  'Seal',
  'Sloth',
  'Cheetah',
  'Gorilla',
  'Polar Bear',
];
